version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: dev-postgresql
    restart: unless-stopped
    environment:
      POSTGRES_DB: rentafit
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    network_mode: bridge

volumes:
  postgres_data:
    external: true
    name: dev-postgresql-data
