# Configuracoes de Producao para NFS-e Nacional (SVRS)
nfs-e.api.url=https://nfse.svrs.rs.gov.br/
nfs-e.sts.url=https://nfse.svrs.rs.gov.br/api/token
nfs-e.ambiente=1
cors.allowed-origins=http://noivamodas.com.br,http://www.noivamodas.com.br,https://noivamodas.com.br,https://www.noivamodas.com.br
