# Configuracoes de Producao para NFS-e Via (Serpro)
nfs-e.via.recepcao.url=https://producaorestrita.certificado.api.via.nfse.gov.br/recepcao
nfs-e.via.consultas.url=https://producaorestrita.certificado.api.via.nfse.gov.br/concessionarias

# Configuracoes de Producao para NFS-e Nacional (SVRS)
nfs-e.api.url=https://nfse.svrs.rs.gov.br/
nfs-e.sts.url=https://nfse.svrs.rs.gov.br/api/token
nfs-e.ambiente=1
