WITH greatest_numeric_id AS (
    SELECT COALESCE(MAX(legacy_id::INTEGER), 0) AS value
    FROM rental_items
    WHERE legacy_id ~ '^[1-9][0-9]*$'
), replacement_ids AS (
    SELECT
        id,
        greatest_numeric_id.value + ROW_NUMBER() OVER (ORDER BY id) AS value
    FROM rental_items
    CROSS JOIN greatest_numeric_id
    WHERE legacy_id IS NULL
       OR legacy_id !~ '^[1-9][0-9]*$'
)
UPDATE rental_items
SET legacy_id = replacement_ids.value::TEXT
FROM replacement_ids
WHERE rental_items.id = replacement_ids.id;

ALTER TABLE rental_items
    ALTER COLUMN legacy_id TYPE INTEGER
    USING legacy_id::INTEGER,
    ALTER COLUMN legacy_id SET NOT NULL;

ALTER TABLE rental_items
    ADD CONSTRAINT chk_rental_items_legacy_id_positive
    CHECK (legacy_id > 0);

COMMENT ON COLUMN rental_items.legacy_id IS 'Legacy system numeric ID generated by the backend';
