AWSTemplateFormatVersion: '2010-09-09'
Description: 'Recursos de Seguranca e Persistencia (IAM, EFS)'

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
  PrivateSubnet1Id:
    Type: AWS::EC2::Subnet::Id
  PrivateSubnet2Id:
    Type: AWS::EC2::Subnet::Id
  DbPasswordSecretArn:
    Type: String
    Description: ARN do secret no Secrets Manager para DB_PASSWORD

Resources:
  # IAM Role para Execucao da Task do ECS
  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: [ecs-tasks.amazonaws.com]
            Action: [sts:AssumeRole]
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
        - arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess
      Policies:
        - PolicyName: RentafitSecretsManagerRead
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Ref DbPasswordSecretArn

  # IAM Role para a Task em si (Permissoes de Runtime como EFS)
  ECSTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: [ecs-tasks.amazonaws.com]
            Action: [sts:AssumeRole]
      Policies:
        - PolicyName: RentafitEFSPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - elasticfilesystem:ClientMount
                  - elasticfilesystem:ClientWrite
                  - elasticfilesystem:ClientRootAccess
                Resource: !GetAtt HKFileSystem.Arn # Limitado ao ARN do EFS criado abaixo

  # Security Group para o EFS
  EFSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Permite acesso NFS do ECS
      VpcId: !Ref VpcId
      # Ingresso sera criado no stack do ECS com SourceSecurityGroupId

  # EFS para persistncia de dados em HK
  HKFileSystem:
    Type: AWS::EFS::FileSystem
    Properties:
      Encrypted: true
      PerformanceMode: generalPurpose
      FileSystemTags:
        - Key: Name
          Value: Rentafit-HK-DB-Storage

  # Pontos de montagem (Mount Targets) do EFS nas subnets privadas
  MountTarget1:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref HKFileSystem
      SubnetId: !Ref PrivateSubnet1Id
      SecurityGroups: [ !Ref EFSSecurityGroup ]

  MountTarget2:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref HKFileSystem
      SubnetId: !Ref PrivateSubnet2Id
      SecurityGroups: [ !Ref EFSSecurityGroup ]

Outputs:
  ExecutionRoleArn:
    Value: !GetAtt ECSTaskExecutionRole.Arn
  TaskRoleArn:
    Value: !GetAtt ECSTaskRole.Arn
  FileSystemId:
    Value: !Ref HKFileSystem
  EfsSecurityGroupId:
    Value: !Ref EFSSecurityGroup
